on:
  push:
    branches:
      - main
name: Build
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: ./build/vsts-prerequisites.ps1
      shell: pwsh
    - name: Validate
      run: ./build/vsts-validate.ps1
      shell: pwsh
    - name: Build
      run: ./build/vsts-build.ps1 -ApiKey $env:APIKEY -IncludeGitHubRelease
      shell: pwsh
      env:
        APIKEY: ${{ secrets.ApiKey }}
